[package]
name = "toydb"
description = "A distributed SQL database"
version = "0.1.0"
authors = ["Erik Grinaker <erik@grinaker.org>"]
edition = "2021"
default-run = "toydb"

[lib]
doctest = false

[dependencies]
bincode = "1.3.3"
clap = { version = "4.5.4", features = ["cargo", "derive"] }
config = "0.14.0"
crossbeam = { version = "0.8.4", features = ["crossbeam-channel"] }
derivative = "2.2.0"
fs4 = "0.8.2"
hdrhistogram = "7.5.4"
hex = "0.4.3"
itertools = "0.12.1"
log = "0.4.21"
petname = "2.0.2"
rand = "0.8.5"
regex = "1.10.4"
rustyline = "14.0.0"
rustyline-derive = "0.10.0"
serde = "1.0.200"
serde_bytes = "0.11.14"
serde_derive = "1.0.200"
simplelog = "0.12.2"
uuid = { version = "1.8.0", features = ["v4"] }

[dev-dependencies]
escargot = "0.5.10"
goldenfile = "1.7.1"
goldenscript = "0.5.0"
paste = "1.0.14"
pretty_assertions = "1.4.0"
serde_json = "1.0.117"
serial_test = "3.1.1"
tempdir = "0.3.7"
tempfile = "3.10.1"
test_each_file = "0.3.2"
