[package]
name = "toydb"
description = "A distributed SQL database"
version = "0.1.0"
authors = ["Erik Grinaker <erik@grinaker.org>"]
edition = "2021"
default-run = "toydb"

[lib]
doctest = false

[dependencies]
bincode = "~1.3.3"
clap = { version = "~4.3.21", features = ["cargo"] }
config = "~0.13.3"
derivative = "~2.2.0"
fs4 = "0.6.6"
futures = "~0.3.15"
futures-util = "~0.3.15"
hex = "0.4.3"
lazy_static = "~1.4.0"
log = "~0.4.14"
names = "~0.14.0"
rand = "~0.8.3"
regex = "1.5.4"
rustyline = "~12.0.0"
rustyline-derive = "0.9.0"
serde = "~1.0.126"
serde_bytes = "0.11.12"
serde_derive = "~1.0.126"
simplelog = "~0.12.1"
tokio = { version = "~1.31.0", features = [
    "macros",
    "rt",
    "rt-multi-thread",
    "net",
    "io-util",
    "time",
    "sync",
] }
tokio-serde = { version = "~0.8", features = ["bincode"] }
tokio-stream = { version = "~0.1.6", features = ["net"] }
tokio-util = { version = "~0.7.8", features = ["codec"] }
uuid = { version = "~1.4.1", features = ["v4"] }

[dev-dependencies]
goldenfile = "~1.5.2"
paste = "1.0.14"
pretty_assertions = "~1.4.0"
serial_test = "~2.0.0"
tempdir = "~0.3.7"
tempfile = "~3.7.1"
