[package]
name = "toydb"
description = "A distributed SQL database"
version = "0.1.0"
authors = ["Erik Grinaker <erik@grinaker.org>"]
edition = "2018"
default-run = "toydb"

[dependencies]
bincode = "~1.3.3"
clap = "~2.33.3"
config = "~0.11.0"
lexical-core = "0.7.6"
derivative = "~2.2.0"
futures = "~0.3.15"
futures-util = "~0.3.15"
lazy_static = "~1.4.0"
log = "~0.4.14"
names = "~0.11.0"
rand = "~0.8.3"
regex = "1.5.4"
rustyline = "~8.2.0"
rustyline-derive = "0.4.0"
serde = "~1.0.126"
serde_derive = "~1.0.126"
simplelog = "0.10.0"
tokio = { version = "~1.6.2", features = ["macros", "rt", "rt-multi-thread", "net", "io-util", "time", "sync"] }
tokio-serde = { version = "~0.8", features = ["bincode"] }
tokio-stream = { version = "~0.1.6", features = ["net"]}
tokio-util = { version = "~0.6.7", features = ["codec"] }
uuid = { version = "~0.8.2", features = ["v4"] }

[dev-dependencies]
goldenfile = "~1.1.0"
pretty_assertions = "~0.7.2"
serial_test = "~0.5.1"
tempdir = "~0.3.7"
tempfile = "~3.2.0"
