[package]
name = "toydb"
description = "A distributed SQL database"
version = "0.1.0"
authors = ["Erik Grinaker <erik@grinaker.org>"]
edition = "2018"
default-run = "toydb"

[dependencies]
clap = "~2.33.0"
config = "~0.9.3"
derivative = "~2.1.0"
futures = "0.3.4"
futures-util = "0.3.4"
lazy_static = "~1.4.0"
log = "~0.4.6"
names = "0.9.0"
rand = "~0.7.2"
regex = "~1.3.1"
rmp-serde = "~0.14.0"
rustyline = "~5.0.0"
serde = "~1.0.91"
serde_derive = "~1.0.91"
simplelog = "~0.7.4"
tokio = { version = "0.2.18", features = ["macros", "rt-core", "rt-threaded", "net", "tcp", "stream", "io-util", "time", "blocking", "sync"] }
tokio-serde = { version = "0.6.1", features = ["bincode", "cbor"] }
tokio-util = { version = "0.3.1", features = ["codec"] }
uuid = { version = "~0.8.1", features = ["v4"] }

[dev-dependencies]
goldenfile = "~1.1.0"
pretty_assertions = "0.6.1"
serial_test = "~0.4.0"
tempdir = "~0.3.7"
tempfile = "~3.1.0"
